# Generated by Django 3.2 on 2021-11-25 11:08

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 895316))),
            ],
        ),
        migrations.CreateModel(
            name='get_in_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 899306))),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 899306))),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.IntegerField(blank=True, default='0', null=True)),
                ('discription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 897308))),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('Order_status', models.CharField(choices=[('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Processing', max_length=20)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 898308))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, null=True, to='blogapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_subject', models.CharField(max_length=255)),
                ('comment_text', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 14, 896314))),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
