# Generated by Django 3.2 on 2021-11-25 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 583124)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 584121)),
        ),
        migrations.AlterField(
            model_name='get_in_touch',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 587112)),
        ),
        migrations.AlterField(
            model_name='lifestyle',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 587112)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 586115)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 25, 17, 8, 38, 585118)),
        ),
    ]
